version: 0.2.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: nuget restore source\Khala.Processes.sln
build:
  verbosity: minimal
after_build:
- cmd: >-
    nuget pack nuget\Khala.Processes.Abstraction.nuspec

    nuget pack nuget\Khala.Processes.Sql.nuspec
test:
  assemblies: '**\*.tests.dll'
artifacts:
- path: Khala.Processes**.nupkg